package com.africa.crm.businessmanagement.main.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.africa.crm.businessmanagement.main.bean.CompanySalesOrderInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPANY_SALES_ORDER_INFO".
*/
public class CompanySalesOrderInfoDao extends AbstractDao<CompanySalesOrderInfo, Long> {

    public static final String TABLENAME = "COMPANY_SALES_ORDER_INFO";

    /**
     * Properties of entity CompanySalesOrderInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LocalId = new Property(0, Long.class, "localId", true, "_id");
        public final static Property CustomerName = new Property(1, String.class, "customerName", false, "CUSTOMER_NAME");
        public final static Property CreateTime = new Property(2, String.class, "createTime", false, "CREATE_TIME");
        public final static Property CreateTimeDate = new Property(3, Long.class, "createTimeDate", false, "CREATE_TIME_DATE");
        public final static Property SendAddress = new Property(4, String.class, "sendAddress", false, "SEND_ADDRESS");
        public final static Property Remark = new Property(5, String.class, "remark", false, "REMARK");
        public final static Property State = new Property(6, String.class, "state", false, "STATE");
        public final static Property CompanyName = new Property(7, String.class, "companyName", false, "COMPANY_NAME");
        public final static Property UserNickName = new Property(8, String.class, "userNickName", false, "USER_NICK_NAME");
        public final static Property Id = new Property(9, String.class, "id", false, "ID");
        public final static Property EditAble = new Property(10, String.class, "editAble", false, "EDIT_ABLE");
        public final static Property DestinationAddress = new Property(11, String.class, "destinationAddress", false, "DESTINATION_ADDRESS");
        public final static Property ContactName = new Property(12, String.class, "contactName", false, "CONTACT_NAME");
        public final static Property SendAddressZipCode = new Property(13, String.class, "sendAddressZipCode", false, "SEND_ADDRESS_ZIP_CODE");
        public final static Property UserId = new Property(14, String.class, "userId", false, "USER_ID");
        public final static Property Name = new Property(15, String.class, "name", false, "NAME");
        public final static Property StateName = new Property(16, String.class, "stateName", false, "STATE_NAME");
        public final static Property SaleCommission = new Property(17, String.class, "saleCommission", false, "SALE_COMMISSION");
        public final static Property CompanyId = new Property(18, String.class, "companyId", false, "COMPANY_ID");
        public final static Property Products = new Property(19, String.class, "products", false, "PRODUCTS");
        public final static Property Clause = new Property(20, String.class, "clause", false, "CLAUSE");
        public final static Property DestinationAddressZipCode = new Property(21, String.class, "destinationAddressZipCode", false, "DESTINATION_ADDRESS_ZIP_CODE");
        public final static Property Chosen = new Property(22, boolean.class, "chosen", false, "CHOSEN");
        public final static Property IsLocal = new Property(23, boolean.class, "isLocal", false, "IS_LOCAL");
    }


    public CompanySalesOrderInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CompanySalesOrderInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPANY_SALES_ORDER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: localId
                "\"CUSTOMER_NAME\" TEXT," + // 1: customerName
                "\"CREATE_TIME\" TEXT," + // 2: createTime
                "\"CREATE_TIME_DATE\" INTEGER," + // 3: createTimeDate
                "\"SEND_ADDRESS\" TEXT," + // 4: sendAddress
                "\"REMARK\" TEXT," + // 5: remark
                "\"STATE\" TEXT," + // 6: state
                "\"COMPANY_NAME\" TEXT," + // 7: companyName
                "\"USER_NICK_NAME\" TEXT," + // 8: userNickName
                "\"ID\" TEXT," + // 9: id
                "\"EDIT_ABLE\" TEXT," + // 10: editAble
                "\"DESTINATION_ADDRESS\" TEXT," + // 11: destinationAddress
                "\"CONTACT_NAME\" TEXT," + // 12: contactName
                "\"SEND_ADDRESS_ZIP_CODE\" TEXT," + // 13: sendAddressZipCode
                "\"USER_ID\" TEXT," + // 14: userId
                "\"NAME\" TEXT," + // 15: name
                "\"STATE_NAME\" TEXT," + // 16: stateName
                "\"SALE_COMMISSION\" TEXT," + // 17: saleCommission
                "\"COMPANY_ID\" TEXT," + // 18: companyId
                "\"PRODUCTS\" TEXT," + // 19: products
                "\"CLAUSE\" TEXT," + // 20: clause
                "\"DESTINATION_ADDRESS_ZIP_CODE\" TEXT," + // 21: destinationAddressZipCode
                "\"CHOSEN\" INTEGER NOT NULL ," + // 22: chosen
                "\"IS_LOCAL\" INTEGER NOT NULL );"); // 23: isLocal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPANY_SALES_ORDER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CompanySalesOrderInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String customerName = entity.getCustomerName();
        if (customerName != null) {
            stmt.bindString(2, customerName);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(3, createTime);
        }
 
        Long createTimeDate = entity.getCreateTimeDate();
        if (createTimeDate != null) {
            stmt.bindLong(4, createTimeDate);
        }
 
        String sendAddress = entity.getSendAddress();
        if (sendAddress != null) {
            stmt.bindString(5, sendAddress);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(6, remark);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(7, state);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(8, companyName);
        }
 
        String userNickName = entity.getUserNickName();
        if (userNickName != null) {
            stmt.bindString(9, userNickName);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(10, id);
        }
 
        String editAble = entity.getEditAble();
        if (editAble != null) {
            stmt.bindString(11, editAble);
        }
 
        String destinationAddress = entity.getDestinationAddress();
        if (destinationAddress != null) {
            stmt.bindString(12, destinationAddress);
        }
 
        String contactName = entity.getContactName();
        if (contactName != null) {
            stmt.bindString(13, contactName);
        }
 
        String sendAddressZipCode = entity.getSendAddressZipCode();
        if (sendAddressZipCode != null) {
            stmt.bindString(14, sendAddressZipCode);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(15, userId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(16, name);
        }
 
        String stateName = entity.getStateName();
        if (stateName != null) {
            stmt.bindString(17, stateName);
        }
 
        String saleCommission = entity.getSaleCommission();
        if (saleCommission != null) {
            stmt.bindString(18, saleCommission);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(19, companyId);
        }
 
        String products = entity.getProducts();
        if (products != null) {
            stmt.bindString(20, products);
        }
 
        String clause = entity.getClause();
        if (clause != null) {
            stmt.bindString(21, clause);
        }
 
        String destinationAddressZipCode = entity.getDestinationAddressZipCode();
        if (destinationAddressZipCode != null) {
            stmt.bindString(22, destinationAddressZipCode);
        }
        stmt.bindLong(23, entity.getChosen() ? 1L: 0L);
        stmt.bindLong(24, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CompanySalesOrderInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String customerName = entity.getCustomerName();
        if (customerName != null) {
            stmt.bindString(2, customerName);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(3, createTime);
        }
 
        Long createTimeDate = entity.getCreateTimeDate();
        if (createTimeDate != null) {
            stmt.bindLong(4, createTimeDate);
        }
 
        String sendAddress = entity.getSendAddress();
        if (sendAddress != null) {
            stmt.bindString(5, sendAddress);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(6, remark);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(7, state);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(8, companyName);
        }
 
        String userNickName = entity.getUserNickName();
        if (userNickName != null) {
            stmt.bindString(9, userNickName);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(10, id);
        }
 
        String editAble = entity.getEditAble();
        if (editAble != null) {
            stmt.bindString(11, editAble);
        }
 
        String destinationAddress = entity.getDestinationAddress();
        if (destinationAddress != null) {
            stmt.bindString(12, destinationAddress);
        }
 
        String contactName = entity.getContactName();
        if (contactName != null) {
            stmt.bindString(13, contactName);
        }
 
        String sendAddressZipCode = entity.getSendAddressZipCode();
        if (sendAddressZipCode != null) {
            stmt.bindString(14, sendAddressZipCode);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(15, userId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(16, name);
        }
 
        String stateName = entity.getStateName();
        if (stateName != null) {
            stmt.bindString(17, stateName);
        }
 
        String saleCommission = entity.getSaleCommission();
        if (saleCommission != null) {
            stmt.bindString(18, saleCommission);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(19, companyId);
        }
 
        String products = entity.getProducts();
        if (products != null) {
            stmt.bindString(20, products);
        }
 
        String clause = entity.getClause();
        if (clause != null) {
            stmt.bindString(21, clause);
        }
 
        String destinationAddressZipCode = entity.getDestinationAddressZipCode();
        if (destinationAddressZipCode != null) {
            stmt.bindString(22, destinationAddressZipCode);
        }
        stmt.bindLong(23, entity.getChosen() ? 1L: 0L);
        stmt.bindLong(24, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CompanySalesOrderInfo readEntity(Cursor cursor, int offset) {
        CompanySalesOrderInfo entity = new CompanySalesOrderInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // localId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // customerName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // createTime
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // createTimeDate
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // sendAddress
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // remark
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // state
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // companyName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // userNickName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // id
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // editAble
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // destinationAddress
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // contactName
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // sendAddressZipCode
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // userId
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // name
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // stateName
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // saleCommission
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // companyId
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // products
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // clause
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // destinationAddressZipCode
            cursor.getShort(offset + 22) != 0, // chosen
            cursor.getShort(offset + 23) != 0 // isLocal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CompanySalesOrderInfo entity, int offset) {
        entity.setLocalId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCustomerName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreateTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreateTimeDate(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setSendAddress(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRemark(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setState(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCompanyName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUserNickName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setId(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setEditAble(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setDestinationAddress(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setContactName(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setSendAddressZipCode(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setUserId(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setName(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setStateName(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setSaleCommission(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setCompanyId(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setProducts(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setClause(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setDestinationAddressZipCode(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setChosen(cursor.getShort(offset + 22) != 0);
        entity.setIsLocal(cursor.getShort(offset + 23) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CompanySalesOrderInfo entity, long rowId) {
        entity.setLocalId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CompanySalesOrderInfo entity) {
        if(entity != null) {
            return entity.getLocalId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CompanySalesOrderInfo entity) {
        return entity.getLocalId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
