package com.africa.crm.businessmanagement.main.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.africa.crm.businessmanagement.main.bean.CompanyPackagingDataInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPANY_PACKAGING_DATA_INFO".
*/
public class CompanyPackagingDataInfoDao extends AbstractDao<CompanyPackagingDataInfo, Long> {

    public static final String TABLENAME = "COMPANY_PACKAGING_DATA_INFO";

    /**
     * Properties of entity CompanyPackagingDataInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LocalId = new Property(0, Long.class, "localId", true, "_id");
        public final static Property Id = new Property(1, String.class, "id", false, "ID");
        public final static Property StartDate = new Property(2, String.class, "startDate", false, "START_DATE");
        public final static Property CreateTime = new Property(3, String.class, "createTime", false, "CREATE_TIME");
        public final static Property CreateTimeDate = new Property(4, Long.class, "createTimeDate", false, "CREATE_TIME_DATE");
        public final static Property Num = new Property(5, String.class, "num", false, "NUM");
        public final static Property Remark = new Property(6, String.class, "remark", false, "REMARK");
        public final static Property PreviewInfo = new Property(7, String.class, "previewInfo", false, "PREVIEW_INFO");
        public final static Property UserId = new Property(8, String.class, "userId", false, "USER_ID");
        public final static Property EndDate = new Property(9, String.class, "endDate", false, "END_DATE");
        public final static Property CompanyId = new Property(10, String.class, "companyId", false, "COMPANY_ID");
        public final static Property CompanyName = new Property(11, String.class, "companyName", false, "COMPANY_NAME");
        public final static Property UserNickName = new Property(12, String.class, "userNickName", false, "USER_NICK_NAME");
        public final static Property Chosen = new Property(13, boolean.class, "chosen", false, "CHOSEN");
    }


    public CompanyPackagingDataInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CompanyPackagingDataInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPANY_PACKAGING_DATA_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: localId
                "\"ID\" TEXT," + // 1: id
                "\"START_DATE\" TEXT," + // 2: startDate
                "\"CREATE_TIME\" TEXT," + // 3: createTime
                "\"CREATE_TIME_DATE\" INTEGER," + // 4: createTimeDate
                "\"NUM\" TEXT," + // 5: num
                "\"REMARK\" TEXT," + // 6: remark
                "\"PREVIEW_INFO\" TEXT," + // 7: previewInfo
                "\"USER_ID\" TEXT," + // 8: userId
                "\"END_DATE\" TEXT," + // 9: endDate
                "\"COMPANY_ID\" TEXT," + // 10: companyId
                "\"COMPANY_NAME\" TEXT," + // 11: companyName
                "\"USER_NICK_NAME\" TEXT," + // 12: userNickName
                "\"CHOSEN\" INTEGER NOT NULL );"); // 13: chosen
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPANY_PACKAGING_DATA_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CompanyPackagingDataInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(3, startDate);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(4, createTime);
        }
 
        Long createTimeDate = entity.getCreateTimeDate();
        if (createTimeDate != null) {
            stmt.bindLong(5, createTimeDate);
        }
 
        String num = entity.getNum();
        if (num != null) {
            stmt.bindString(6, num);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(7, remark);
        }
 
        String previewInfo = entity.getPreviewInfo();
        if (previewInfo != null) {
            stmt.bindString(8, previewInfo);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(9, userId);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(10, endDate);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(11, companyId);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(12, companyName);
        }
 
        String userNickName = entity.getUserNickName();
        if (userNickName != null) {
            stmt.bindString(13, userNickName);
        }
        stmt.bindLong(14, entity.getChosen() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CompanyPackagingDataInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(3, startDate);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(4, createTime);
        }
 
        Long createTimeDate = entity.getCreateTimeDate();
        if (createTimeDate != null) {
            stmt.bindLong(5, createTimeDate);
        }
 
        String num = entity.getNum();
        if (num != null) {
            stmt.bindString(6, num);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(7, remark);
        }
 
        String previewInfo = entity.getPreviewInfo();
        if (previewInfo != null) {
            stmt.bindString(8, previewInfo);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(9, userId);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(10, endDate);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(11, companyId);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(12, companyName);
        }
 
        String userNickName = entity.getUserNickName();
        if (userNickName != null) {
            stmt.bindString(13, userNickName);
        }
        stmt.bindLong(14, entity.getChosen() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CompanyPackagingDataInfo readEntity(Cursor cursor, int offset) {
        CompanyPackagingDataInfo entity = new CompanyPackagingDataInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // localId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // startDate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // createTime
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // createTimeDate
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // num
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // remark
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // previewInfo
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // userId
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // endDate
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // companyId
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // companyName
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // userNickName
            cursor.getShort(offset + 13) != 0 // chosen
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CompanyPackagingDataInfo entity, int offset) {
        entity.setLocalId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStartDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreateTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreateTimeDate(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setNum(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRemark(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPreviewInfo(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUserId(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setEndDate(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCompanyId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCompanyName(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setUserNickName(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setChosen(cursor.getShort(offset + 13) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CompanyPackagingDataInfo entity, long rowId) {
        entity.setLocalId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CompanyPackagingDataInfo entity) {
        if(entity != null) {
            return entity.getLocalId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CompanyPackagingDataInfo entity) {
        return entity.getLocalId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
