package com.africa.crm.businessmanagement.main.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.africa.crm.businessmanagement.main.bean.delete.CompanyDeleteContactInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPANY_DELETE_CONTACT_INFO".
*/
public class CompanyDeleteContactInfoDao extends AbstractDao<CompanyDeleteContactInfo, Long> {

    public static final String TABLENAME = "COMPANY_DELETE_CONTACT_INFO";

    /**
     * Properties of entity CompanyDeleteContactInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LocalId = new Property(0, Long.class, "localId", true, "_id");
        public final static Property Id = new Property(1, String.class, "id", false, "ID");
        public final static Property CreateTime = new Property(2, String.class, "createTime", false, "CREATE_TIME");
        public final static Property Address = new Property(3, String.class, "address", false, "ADDRESS");
        public final static Property CompanyName = new Property(4, String.class, "companyName", false, "COMPANY_NAME");
        public final static Property MailAddress = new Property(5, String.class, "mailAddress", false, "MAIL_ADDRESS");
        public final static Property Remark = new Property(6, String.class, "remark", false, "REMARK");
        public final static Property UserId = new Property(7, String.class, "userId", false, "USER_ID");
        public final static Property FromTypeName = new Property(8, String.class, "fromTypeName", false, "FROM_TYPE_NAME");
        public final static Property Head = new Property(9, String.class, "head", false, "HEAD");
        public final static Property CompanyId = new Property(10, String.class, "companyId", false, "COMPANY_ID");
        public final static Property FromType = new Property(11, String.class, "fromType", false, "FROM_TYPE");
        public final static Property Phone = new Property(12, String.class, "phone", false, "PHONE");
        public final static Property Name = new Property(13, String.class, "name", false, "NAME");
        public final static Property Tel = new Property(14, String.class, "tel", false, "TEL");
        public final static Property UserNickName = new Property(15, String.class, "userNickName", false, "USER_NICK_NAME");
        public final static Property Job = new Property(16, String.class, "job", false, "JOB");
        public final static Property Email = new Property(17, String.class, "email", false, "EMAIL");
        public final static Property Chosen = new Property(18, boolean.class, "chosen", false, "CHOSEN");
        public final static Property IsLocal = new Property(19, boolean.class, "isLocal", false, "IS_LOCAL");
    }


    public CompanyDeleteContactInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CompanyDeleteContactInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPANY_DELETE_CONTACT_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: localId
                "\"ID\" TEXT," + // 1: id
                "\"CREATE_TIME\" TEXT," + // 2: createTime
                "\"ADDRESS\" TEXT," + // 3: address
                "\"COMPANY_NAME\" TEXT," + // 4: companyName
                "\"MAIL_ADDRESS\" TEXT," + // 5: mailAddress
                "\"REMARK\" TEXT," + // 6: remark
                "\"USER_ID\" TEXT," + // 7: userId
                "\"FROM_TYPE_NAME\" TEXT," + // 8: fromTypeName
                "\"HEAD\" TEXT," + // 9: head
                "\"COMPANY_ID\" TEXT," + // 10: companyId
                "\"FROM_TYPE\" TEXT," + // 11: fromType
                "\"PHONE\" TEXT," + // 12: phone
                "\"NAME\" TEXT," + // 13: name
                "\"TEL\" TEXT," + // 14: tel
                "\"USER_NICK_NAME\" TEXT," + // 15: userNickName
                "\"JOB\" TEXT," + // 16: job
                "\"EMAIL\" TEXT," + // 17: email
                "\"CHOSEN\" INTEGER NOT NULL ," + // 18: chosen
                "\"IS_LOCAL\" INTEGER NOT NULL );"); // 19: isLocal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPANY_DELETE_CONTACT_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CompanyDeleteContactInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(3, createTime);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(4, address);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(5, companyName);
        }
 
        String mailAddress = entity.getMailAddress();
        if (mailAddress != null) {
            stmt.bindString(6, mailAddress);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(7, remark);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(8, userId);
        }
 
        String fromTypeName = entity.getFromTypeName();
        if (fromTypeName != null) {
            stmt.bindString(9, fromTypeName);
        }
 
        String head = entity.getHead();
        if (head != null) {
            stmt.bindString(10, head);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(11, companyId);
        }
 
        String fromType = entity.getFromType();
        if (fromType != null) {
            stmt.bindString(12, fromType);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(13, phone);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(14, name);
        }
 
        String tel = entity.getTel();
        if (tel != null) {
            stmt.bindString(15, tel);
        }
 
        String userNickName = entity.getUserNickName();
        if (userNickName != null) {
            stmt.bindString(16, userNickName);
        }
 
        String job = entity.getJob();
        if (job != null) {
            stmt.bindString(17, job);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(18, email);
        }
        stmt.bindLong(19, entity.getChosen() ? 1L: 0L);
        stmt.bindLong(20, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CompanyDeleteContactInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(3, createTime);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(4, address);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(5, companyName);
        }
 
        String mailAddress = entity.getMailAddress();
        if (mailAddress != null) {
            stmt.bindString(6, mailAddress);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(7, remark);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(8, userId);
        }
 
        String fromTypeName = entity.getFromTypeName();
        if (fromTypeName != null) {
            stmt.bindString(9, fromTypeName);
        }
 
        String head = entity.getHead();
        if (head != null) {
            stmt.bindString(10, head);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(11, companyId);
        }
 
        String fromType = entity.getFromType();
        if (fromType != null) {
            stmt.bindString(12, fromType);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(13, phone);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(14, name);
        }
 
        String tel = entity.getTel();
        if (tel != null) {
            stmt.bindString(15, tel);
        }
 
        String userNickName = entity.getUserNickName();
        if (userNickName != null) {
            stmt.bindString(16, userNickName);
        }
 
        String job = entity.getJob();
        if (job != null) {
            stmt.bindString(17, job);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(18, email);
        }
        stmt.bindLong(19, entity.getChosen() ? 1L: 0L);
        stmt.bindLong(20, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CompanyDeleteContactInfo readEntity(Cursor cursor, int offset) {
        CompanyDeleteContactInfo entity = new CompanyDeleteContactInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // localId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // createTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // address
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // companyName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // mailAddress
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // remark
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // userId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // fromTypeName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // head
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // companyId
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // fromType
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // phone
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // name
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // tel
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // userNickName
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // job
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // email
            cursor.getShort(offset + 18) != 0, // chosen
            cursor.getShort(offset + 19) != 0 // isLocal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CompanyDeleteContactInfo entity, int offset) {
        entity.setLocalId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreateTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAddress(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCompanyName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMailAddress(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRemark(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUserId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFromTypeName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setHead(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCompanyId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFromType(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setPhone(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setName(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setTel(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setUserNickName(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setJob(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setEmail(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setChosen(cursor.getShort(offset + 18) != 0);
        entity.setIsLocal(cursor.getShort(offset + 19) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CompanyDeleteContactInfo entity, long rowId) {
        entity.setLocalId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CompanyDeleteContactInfo entity) {
        if(entity != null) {
            return entity.getLocalId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CompanyDeleteContactInfo entity) {
        return entity.getLocalId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
