package com.africa.crm.businessmanagement.main.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.africa.crm.businessmanagement.main.bean.CompanyTradingOrderInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPANY_TRADING_ORDER_INFO".
*/
public class CompanyTradingOrderInfoDao extends AbstractDao<CompanyTradingOrderInfo, Long> {

    public static final String TABLENAME = "COMPANY_TRADING_ORDER_INFO";

    /**
     * Properties of entity CompanyTradingOrderInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LocalId = new Property(0, Long.class, "localId", true, "_id");
        public final static Property CustomerName = new Property(1, String.class, "customerName", false, "CUSTOMER_NAME");
        public final static Property CreateTimeDate = new Property(2, Long.class, "createTimeDate", false, "CREATE_TIME_DATE");
        public final static Property CreateTime = new Property(3, String.class, "createTime", false, "CREATE_TIME");
        public final static Property Remark = new Property(4, String.class, "remark", false, "REMARK");
        public final static Property ClueSource = new Property(5, String.class, "clueSource", false, "CLUE_SOURCE");
        public final static Property Possibility = new Property(6, String.class, "possibility", false, "POSSIBILITY");
        public final static Property CompanyName = new Property(7, String.class, "companyName", false, "COMPANY_NAME");
        public final static Property UserNickName = new Property(8, String.class, "userNickName", false, "USER_NICK_NAME");
        public final static Property Id = new Property(9, String.class, "id", false, "ID");
        public final static Property EstimateProfit = new Property(10, String.class, "estimateProfit", false, "ESTIMATE_PROFIT");
        public final static Property Price = new Property(11, String.class, "price", false, "PRICE");
        public final static Property EditAble = new Property(12, String.class, "editAble", false, "EDIT_ABLE");
        public final static Property ContactName = new Property(13, String.class, "contactName", false, "CONTACT_NAME");
        public final static Property UserId = new Property(14, String.class, "userId", false, "USER_ID");
        public final static Property Name = new Property(15, String.class, "name", false, "NAME");
        public final static Property CompanyId = new Property(16, String.class, "companyId", false, "COMPANY_ID");
        public final static Property Chosen = new Property(17, boolean.class, "chosen", false, "CHOSEN");
        public final static Property IsLocal = new Property(18, boolean.class, "isLocal", false, "IS_LOCAL");
    }


    public CompanyTradingOrderInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CompanyTradingOrderInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPANY_TRADING_ORDER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: localId
                "\"CUSTOMER_NAME\" TEXT," + // 1: customerName
                "\"CREATE_TIME_DATE\" INTEGER," + // 2: createTimeDate
                "\"CREATE_TIME\" TEXT," + // 3: createTime
                "\"REMARK\" TEXT," + // 4: remark
                "\"CLUE_SOURCE\" TEXT," + // 5: clueSource
                "\"POSSIBILITY\" TEXT," + // 6: possibility
                "\"COMPANY_NAME\" TEXT," + // 7: companyName
                "\"USER_NICK_NAME\" TEXT," + // 8: userNickName
                "\"ID\" TEXT," + // 9: id
                "\"ESTIMATE_PROFIT\" TEXT," + // 10: estimateProfit
                "\"PRICE\" TEXT," + // 11: price
                "\"EDIT_ABLE\" TEXT," + // 12: editAble
                "\"CONTACT_NAME\" TEXT," + // 13: contactName
                "\"USER_ID\" TEXT," + // 14: userId
                "\"NAME\" TEXT," + // 15: name
                "\"COMPANY_ID\" TEXT," + // 16: companyId
                "\"CHOSEN\" INTEGER NOT NULL ," + // 17: chosen
                "\"IS_LOCAL\" INTEGER NOT NULL );"); // 18: isLocal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPANY_TRADING_ORDER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CompanyTradingOrderInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String customerName = entity.getCustomerName();
        if (customerName != null) {
            stmt.bindString(2, customerName);
        }
 
        Long createTimeDate = entity.getCreateTimeDate();
        if (createTimeDate != null) {
            stmt.bindLong(3, createTimeDate);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(4, createTime);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        String clueSource = entity.getClueSource();
        if (clueSource != null) {
            stmt.bindString(6, clueSource);
        }
 
        String possibility = entity.getPossibility();
        if (possibility != null) {
            stmt.bindString(7, possibility);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(8, companyName);
        }
 
        String userNickName = entity.getUserNickName();
        if (userNickName != null) {
            stmt.bindString(9, userNickName);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(10, id);
        }
 
        String estimateProfit = entity.getEstimateProfit();
        if (estimateProfit != null) {
            stmt.bindString(11, estimateProfit);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(12, price);
        }
 
        String editAble = entity.getEditAble();
        if (editAble != null) {
            stmt.bindString(13, editAble);
        }
 
        String contactName = entity.getContactName();
        if (contactName != null) {
            stmt.bindString(14, contactName);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(15, userId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(16, name);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(17, companyId);
        }
        stmt.bindLong(18, entity.getChosen() ? 1L: 0L);
        stmt.bindLong(19, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CompanyTradingOrderInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String customerName = entity.getCustomerName();
        if (customerName != null) {
            stmt.bindString(2, customerName);
        }
 
        Long createTimeDate = entity.getCreateTimeDate();
        if (createTimeDate != null) {
            stmt.bindLong(3, createTimeDate);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(4, createTime);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        String clueSource = entity.getClueSource();
        if (clueSource != null) {
            stmt.bindString(6, clueSource);
        }
 
        String possibility = entity.getPossibility();
        if (possibility != null) {
            stmt.bindString(7, possibility);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(8, companyName);
        }
 
        String userNickName = entity.getUserNickName();
        if (userNickName != null) {
            stmt.bindString(9, userNickName);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(10, id);
        }
 
        String estimateProfit = entity.getEstimateProfit();
        if (estimateProfit != null) {
            stmt.bindString(11, estimateProfit);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(12, price);
        }
 
        String editAble = entity.getEditAble();
        if (editAble != null) {
            stmt.bindString(13, editAble);
        }
 
        String contactName = entity.getContactName();
        if (contactName != null) {
            stmt.bindString(14, contactName);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(15, userId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(16, name);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(17, companyId);
        }
        stmt.bindLong(18, entity.getChosen() ? 1L: 0L);
        stmt.bindLong(19, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CompanyTradingOrderInfo readEntity(Cursor cursor, int offset) {
        CompanyTradingOrderInfo entity = new CompanyTradingOrderInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // localId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // customerName
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // createTimeDate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // createTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // remark
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // clueSource
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // possibility
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // companyName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // userNickName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // id
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // estimateProfit
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // price
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // editAble
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // contactName
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // userId
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // name
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // companyId
            cursor.getShort(offset + 17) != 0, // chosen
            cursor.getShort(offset + 18) != 0 // isLocal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CompanyTradingOrderInfo entity, int offset) {
        entity.setLocalId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCustomerName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreateTimeDate(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setCreateTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRemark(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setClueSource(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPossibility(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCompanyName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUserNickName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setId(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setEstimateProfit(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setPrice(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setEditAble(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setContactName(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setUserId(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setName(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setCompanyId(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setChosen(cursor.getShort(offset + 17) != 0);
        entity.setIsLocal(cursor.getShort(offset + 18) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CompanyTradingOrderInfo entity, long rowId) {
        entity.setLocalId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CompanyTradingOrderInfo entity) {
        if(entity != null) {
            return entity.getLocalId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CompanyTradingOrderInfo entity) {
        return entity.getLocalId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
