package com.africa.crm.businessmanagement.main.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.africa.crm.businessmanagement.main.bean.delete.CompanyDeleteProductInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPANY_DELETE_PRODUCT_INFO".
*/
public class CompanyDeleteProductInfoDao extends AbstractDao<CompanyDeleteProductInfo, Long> {

    public static final String TABLENAME = "COMPANY_DELETE_PRODUCT_INFO";

    /**
     * Properties of entity CompanyDeleteProductInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LocalId = new Property(0, Long.class, "localId", true, "_id");
        public final static Property CreateTime = new Property(1, String.class, "createTime", false, "CREATE_TIME");
        public final static Property SupplierName = new Property(2, String.class, "supplierName", false, "SUPPLIER_NAME");
        public final static Property Remark = new Property(3, String.class, "remark", false, "REMARK");
        public final static Property StockNum = new Property(4, String.class, "stockNum", false, "STOCK_NUM");
        public final static Property UnitPrice = new Property(5, String.class, "unitPrice", false, "UNIT_PRICE");
        public final static Property Code = new Property(6, String.class, "code", false, "CODE");
        public final static Property CompanyName = new Property(7, String.class, "companyName", false, "COMPANY_NAME");
        public final static Property Type = new Property(8, String.class, "type", false, "TYPE");
        public final static Property WarnNum = new Property(9, String.class, "warnNum", false, "WARN_NUM");
        public final static Property Id = new Property(10, String.class, "id", false, "ID");
        public final static Property TypeName = new Property(11, String.class, "typeName", false, "TYPE_NAME");
        public final static Property Unit = new Property(12, String.class, "unit", false, "UNIT");
        public final static Property Name = new Property(13, String.class, "name", false, "NAME");
        public final static Property CompanyId = new Property(14, String.class, "companyId", false, "COMPANY_ID");
        public final static Property MakerName = new Property(15, String.class, "makerName", false, "MAKER_NAME");
        public final static Property Chosen = new Property(16, boolean.class, "chosen", false, "CHOSEN");
        public final static Property IsLocal = new Property(17, boolean.class, "isLocal", false, "IS_LOCAL");
    }


    public CompanyDeleteProductInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CompanyDeleteProductInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPANY_DELETE_PRODUCT_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: localId
                "\"CREATE_TIME\" TEXT," + // 1: createTime
                "\"SUPPLIER_NAME\" TEXT," + // 2: supplierName
                "\"REMARK\" TEXT," + // 3: remark
                "\"STOCK_NUM\" TEXT," + // 4: stockNum
                "\"UNIT_PRICE\" TEXT," + // 5: unitPrice
                "\"CODE\" TEXT," + // 6: code
                "\"COMPANY_NAME\" TEXT," + // 7: companyName
                "\"TYPE\" TEXT," + // 8: type
                "\"WARN_NUM\" TEXT," + // 9: warnNum
                "\"ID\" TEXT," + // 10: id
                "\"TYPE_NAME\" TEXT," + // 11: typeName
                "\"UNIT\" TEXT," + // 12: unit
                "\"NAME\" TEXT," + // 13: name
                "\"COMPANY_ID\" TEXT," + // 14: companyId
                "\"MAKER_NAME\" TEXT," + // 15: makerName
                "\"CHOSEN\" INTEGER NOT NULL ," + // 16: chosen
                "\"IS_LOCAL\" INTEGER NOT NULL );"); // 17: isLocal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPANY_DELETE_PRODUCT_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CompanyDeleteProductInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(2, createTime);
        }
 
        String supplierName = entity.getSupplierName();
        if (supplierName != null) {
            stmt.bindString(3, supplierName);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(4, remark);
        }
 
        String stockNum = entity.getStockNum();
        if (stockNum != null) {
            stmt.bindString(5, stockNum);
        }
 
        String unitPrice = entity.getUnitPrice();
        if (unitPrice != null) {
            stmt.bindString(6, unitPrice);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(7, code);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(8, companyName);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(9, type);
        }
 
        String warnNum = entity.getWarnNum();
        if (warnNum != null) {
            stmt.bindString(10, warnNum);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(11, id);
        }
 
        String typeName = entity.getTypeName();
        if (typeName != null) {
            stmt.bindString(12, typeName);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(13, unit);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(14, name);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(15, companyId);
        }
 
        String makerName = entity.getMakerName();
        if (makerName != null) {
            stmt.bindString(16, makerName);
        }
        stmt.bindLong(17, entity.getChosen() ? 1L: 0L);
        stmt.bindLong(18, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CompanyDeleteProductInfo entity) {
        stmt.clearBindings();
 
        Long localId = entity.getLocalId();
        if (localId != null) {
            stmt.bindLong(1, localId);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(2, createTime);
        }
 
        String supplierName = entity.getSupplierName();
        if (supplierName != null) {
            stmt.bindString(3, supplierName);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(4, remark);
        }
 
        String stockNum = entity.getStockNum();
        if (stockNum != null) {
            stmt.bindString(5, stockNum);
        }
 
        String unitPrice = entity.getUnitPrice();
        if (unitPrice != null) {
            stmt.bindString(6, unitPrice);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(7, code);
        }
 
        String companyName = entity.getCompanyName();
        if (companyName != null) {
            stmt.bindString(8, companyName);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(9, type);
        }
 
        String warnNum = entity.getWarnNum();
        if (warnNum != null) {
            stmt.bindString(10, warnNum);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(11, id);
        }
 
        String typeName = entity.getTypeName();
        if (typeName != null) {
            stmt.bindString(12, typeName);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(13, unit);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(14, name);
        }
 
        String companyId = entity.getCompanyId();
        if (companyId != null) {
            stmt.bindString(15, companyId);
        }
 
        String makerName = entity.getMakerName();
        if (makerName != null) {
            stmt.bindString(16, makerName);
        }
        stmt.bindLong(17, entity.getChosen() ? 1L: 0L);
        stmt.bindLong(18, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CompanyDeleteProductInfo readEntity(Cursor cursor, int offset) {
        CompanyDeleteProductInfo entity = new CompanyDeleteProductInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // localId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // createTime
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // supplierName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // remark
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // stockNum
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // unitPrice
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // code
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // companyName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // type
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // warnNum
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // id
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // typeName
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // unit
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // name
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // companyId
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // makerName
            cursor.getShort(offset + 16) != 0, // chosen
            cursor.getShort(offset + 17) != 0 // isLocal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CompanyDeleteProductInfo entity, int offset) {
        entity.setLocalId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCreateTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSupplierName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRemark(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStockNum(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUnitPrice(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCode(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCompanyName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setType(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setWarnNum(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTypeName(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setUnit(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setName(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCompanyId(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setMakerName(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setChosen(cursor.getShort(offset + 16) != 0);
        entity.setIsLocal(cursor.getShort(offset + 17) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CompanyDeleteProductInfo entity, long rowId) {
        entity.setLocalId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CompanyDeleteProductInfo entity) {
        if(entity != null) {
            return entity.getLocalId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CompanyDeleteProductInfo entity) {
        return entity.getLocalId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
