package com.africa.crm.businessmanagement.main.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.africa.crm.businessmanagement.main.bean.LoginInfoBean;

import com.africa.crm.businessmanagement.main.dao.LoginInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginInfoBeanDaoConfig;

    private final LoginInfoBeanDao loginInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginInfoBeanDaoConfig = daoConfigMap.get(LoginInfoBeanDao.class).clone();
        loginInfoBeanDaoConfig.initIdentityScope(type);

        loginInfoBeanDao = new LoginInfoBeanDao(loginInfoBeanDaoConfig, this);

        registerDao(LoginInfoBean.class, loginInfoBeanDao);
    }
    
    public void clear() {
        loginInfoBeanDaoConfig.clearIdentityScope();
    }

    public LoginInfoBeanDao getLoginInfoBeanDao() {
        return loginInfoBeanDao;
    }

}
